/*
 * defines.h
 *
 *  Created on: 20 avr. 2022
 *      Author: Garnier
 */

#ifndef DEFINES_H_
#define DEFINES_H_

#define DIALOG_BOX_TITLE				("C-Controls")
#define DIALOG_DATA_STORAGE	   	        ("./Resources/Data")
#define DIALOG_BOX_WIDTH				(1000)
#define DIALOG_BOX_HEIGHT				(380)
#define DIALOG_BOX_PADDING				(10)
#define DIALOG_BOX_PADDING_BUTTON		(30)
#define DIALOG_BOX_PADDING_LINEEDIT 	(220)

#define DIALOG_BOX_LABEL_HEIGHT			(30)
#define DIALOG_BOX_LABEL_WIDTH			(200)

#define DIALOG_BOX_EDIT_HEIGHT			(30)
#define DIALOG_BOX_EDIT_WIDTH			(350)

#define DIALOG_BOX_PIC_HEIGHT			(250)
#define DIALOG_BOX_PIC_WIDTH			(250)

#define DIALOG_BOX_BUTTON_HEIGHT		(30)

#define DIALOG_BOX_BUTTONRIGHT_WIDTH 	(120)
#define DIALOG_BOX_BUTTONLEFT_WIDTH 	(50)


enum e_controlIDs{
	CTRL_ID_LASTNAME_LABEL =100,
	CTRL_ID_FIRSTNAME_LABEL,
	CTRL_ID_DATE_LABEL,
	CTRL_ID_EMAIL_LABEL,
	CTRL_ID_PCITURE_LABEL,
	CTRL_ID_PAGE_LABEL,
	CTRL_ID_ERROR_LABEL,

	CTRL_ID_LASTNAME_LINEEDIT,
	CTRL_ID_FIRSTNAME_LINEEDIT,
	CTRL_ID_DATE_LINEEDIT,
	CTRL_ID_EMAIL_LINEEDIT,

	CTRL_ID_FILENAME_LABEL,
	CTRL_ID_FILENAME_LINEEDIT,

	CTRL_ID_SAVE_PUSHBUTTON,
	CTRL_ID_LOAD_PUSHBUTTON,
	CTRL_ID_EDIT_PUSHBUTTON,
	CTRL_ID_NEW_PUSHBUTTON,
	CTRL_ID_CANCEL_PUSHBUTTON,
	CTRL_ID_APLY_PUSHBUTTON,
	CTRL_ID_ADD_PUSHBUTTON,
	CTRL_ID_DEL_PUSHBUTTON,

	CTRL_ID_EXIT_PUSHBUTTON,
	CTRL_ID_ACTION_PUSHBUTTON,

	CTRL_ID_NAVPREV_PUSHBUTTON,
	CTRL_ID_NAVNEXT_PUSHBUTTON,
	CTRL_ID_NAVBACK_PUSHBUTTON,
	CTRL_ID_NAVFRONT_PUSHBUTTON,

	CTRL_ID_DEBUG_PUSHBUTTON,
};


#endif /* DEFINES_H_ */
